name: Hugo Build Check

on:
  pull_request:
    branches:
      - dev
      - feature/**
    paths:
      - '**/*.md'
      - 'config.toml'
      - 'themes/**'
      - '.github/workflows/hugo_build_check.yml'
      - 'public/**'
      - 'api/**'
  push:
    branches:
      - dev
      - feature/**
    paths:
      - '**/*.md'
      - 'config.toml'
      - 'themes/**'
      - '.github/workflows/hugo_build_check.yml'
      - 'public/**'
      - 'api/**'

jobs:
  hugo_build_check:
    name: Hugo Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build with Hugo
        run: hugo

      - name: Check for public directory
        run: ls public

      - name: Upload artifacts (for debugging)
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: hugo-build-artifacts
          path: public
          if-no-files: error # Fail the workflow if no files are uploaded

      # Add other checks here, like linting, if applicable