name: Hugo Build Check

on:
  pull_request:
    branches:
      - dev
      - feature/** # Matches any feature branch
    # paths:
    #   - '**/*.md' # Example: Markdown files
    #   - 'config.toml' # Hugo config
    #   - 'themes/**' # Hugo themes
    #   - '.github/workflows/hugo_build_check.yml' # This workflow file
    #   - 'public/**' # If you want to check changes in the output directory
    #   - 'api/**' # if you have an api directory
  push:
    branches:
      - dev
      - feature/** # Matches any feature branch

jobs:
  hugo_build_check:
    name: Hugo Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build with Hugo
        run: hugo

      - name: Check for public directory
        run: ls public # Check if the public directory was created

      - name: Upload artifacts (optional, for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: hugo-build-artifacts
          path: public # Or the path to your Hugo output directory
